version: '3.8'

services:
  flask_app:
    build:
      context: https://github.com/nick-danger/business-locator.git
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - NETWORK_MODE=${NETWORK_MODE}
    network_mode: ${NETWORK_MODE}
